extends: ['node-opinionated']
rules: 
  no-underscore-dangle: off
overrides: 
  files: ['**/test/**']
  rules:
    node/no-unpublished-require: off
    max-nested-callbacks: [error, 3]
    max-lines: [warn, 200]
    no-sync: off
    sonarjs/no-duplicate-string: off
    no-console: off
    no-new-function: off
    no-new-wrapper: off
    no-magic-numbers: off

