admin: {hostname: localhost, port: 9876}
apiEndpoints:
  ip: {paths: /ip}
  docs: {paths: /api-docs*}
  api: {paths: '*'}
http: {port: ${GATEWAY_PORT:-7070}}
pipelines:
  ip:
    apiEndpoints: [ip]
    policies:
    - proxy:
      - action: {changeOrigin: true, serviceEndpoint: httpbin}
  open:
    apiEndpoints: [coconutWebhook, docs, webhooks, home]
    policies:
    - log:
      - action:
          message: ${req.method} ${req.originalUrl}
    - proxy:
      - action: {serviceEndpoint: api}

  secured:
    apiEndpoints: [api]
    policies:
    - log:
      - action:
          message: ${req.method} ${req.originalUrl}
    - jwt:
      - action:
          secretOrPublicKey: '...'
    - proxy:
      # - action: {serviceEndpoint: api, prependPath: true, stripPath: true, ignorePath: false}
      - action: {serviceEndpoint: api}
policies: [log, proxy, jwt]
# policies: [basic-auth, cors, expression, key-auth, log, oauth2, proxy, rate-limit, jwt, rewrite]
serviceEndpoints:
  api: {url: 'http://localhost:${APP_PORT:-3333}'}
  httpbin: {url: 'https://httpbin.org'}
